---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{.Values.metadata.name}}
  namespace: {{.Values.metadata.namespace}}
spec:
  version: {{.Values.spec.parameters.esVersion}}
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
